//val kotlin_version: String by extra
//buildscript {
//    var kotlin_version: String by extra
//    kotlin_version = "1.9.20-Beta2"
//    repositories {
//        mavenCentral()
//    }
//    dependencies {
//        classpath(kotlinModule("gradle-plugin", kotlin_version))
//    }
//}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    java
    application
}

repositories {
    mavenCentral()
}

dependencies {

    implementation("com.google.api-client:google-api-client:1.32.1")
    implementation("com.google.oauth-client:google-oauth-client-jetty:1.32.1")
    implementation("com.google.apis:google-api-services-calendar:v3-rev411-1.25.0")

}

application {
    mainClass.set("CalendarQuickstart")
}
